services:
  boilmaster-cht:
    image: ghcr.io/boringwolf/boilmaster:cht
    container_name: boilmaster-cht
    restart: unless-stopped
    ports:
      - "8085:8080" # 對應到 8085 連接埠
    volumes:
      - ./game_cht:/app/game:ro      # 使用獨立的遊戲資料夾
      - ./persist_cht:/app/persist   # 使用獨立的數據存放區
    environment:
      - BM_GAME_DIRECTORY=/app/game
      - BM_READ_LANGUAGE_EXCLUDE=[chs,ko]
      - BM_READ_LANGUAGE_DEFAULT=ja
      - BM_SCHEMA_EXDSCHEMA_REMOTE=https://github.com/xivdev/EXDSchema.git
